
// merge points generated by carta in the step 3b and consolidate into a single asset
// dhemerson.costa@ipam.org.br

// define version of points to consolidate
var version = '31';

// import cerrado feature
var cerrado = ee.FeatureCollection('projects/mapbiomas-workspace/AUXILIAR/biomas-2019')
                .filterMetadata('Bioma', 'equals', 'Cerrado');

// import ibge carta's and filter to cerrado
var cartas = ee.FeatureCollection('projects/mapbiomas-workspace/AUXILIAR/cartas')
              .filterBounds(cerrado);
              
// extract basenames
var basenames = cartas.aggregate_array('grid_name')
                    .remove('SG-21-X-B')
                    .getInfo();
                    
// create empty recipe 
var recipe = ee.FeatureCollection([]);

// for each carta
basenames.forEach(function(file_i) {
  // build filename 
  var filename_i = file_i + '_v' + version;
  print (filename_i);
})
